name: build
on:
  push:
    branch: [main]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - run: mkdir .buildResult
      - name: Build Tizen app
        id: tizen-build-action
        uses: someone120/tizen-build-action@v1.1.1
        with:
          project-dir: ${{ github.workspace }}
          author-key: ${{ secrets.TIZEN_AUTHOR_KEY }}
          author-password: ${{ secrets.TIZEN_AUTHOR_KEY_PW }}

      - name: Upload Tizen package artifact
        uses: actions/upload-artifact@v2
        with:
           name: app-${{ github.sha }}.wgt
           path: ${{ steps.tizen-build-action.outputs.package-artifact }}
